import os
import tempfile
import multiprocessing as mp

from .adjacency_g6 import _structure_to_g6_optimized_worker
from .structures import generate_connected_cotree_structures, generate_all_cotree_structures
from .visualization import render_cotree_jpg


def generate_cographs_final_g6(
        node_count: int,
        output_dir: str = ".",
        connected_only: bool = True,
) -> str:
    """
    Generate cographs with ``node_count`` vertices and save them in graph6 format.

    The output will be written to a file named ``cographs_<node_count>.g6``
    inside ``output_dir``.

    Parameters
    ----------
    node_count : int
        Number of vertices in the cographs to generate.
    output_dir : str, optional
        Directory where the final graph6 file will be written.
    connected_only : bool, optional
        If True, generate only connected cographs (root operator 'J').
        If False, generate all cographs (connected + disconnected).

    Returns
    -------
    str
        Full path of the output file containing graph6 strings.

    Raises
    ------
    NotADirectoryError
        If ``output_dir`` exists and is not a directory.
    """

    total_structures = 0
    total_graph6 = 0

    if os.path.exists(output_dir) and not os.path.isdir(output_dir):
        raise NotADirectoryError(
            f"output_dir must be a directory, got: {output_dir}"
        )

    os.makedirs(output_dir, exist_ok=True)

    output_path = os.path.join(
        output_dir,
        f"cographs_{node_count}.g6"
    )

    num_processes = max(1, mp.cpu_count() // 3)

    if connected_only:
        generator = generate_connected_cotree_structures
    else:
        generator = generate_all_cotree_structures

    with tempfile.NamedTemporaryFile(mode="w+", delete=False) as temp:
        temp_filename = temp.name

        for structure in generator(node_count, 0):
            temp.write(structure + "\n")
            total_structures += 1

    with open(temp_filename, "r") as f_in, open(output_path, "w") as f_out:
        with mp.Pool(num_processes) as pool:
            for g6 in pool.imap(
                _structure_to_g6_optimized_worker,
                f_in,
                chunksize=100
            ):
                f_out.write(g6.strip() + "\n")
                total_graph6 += 1

    os.remove(temp_filename)

    return output_path


def generate_cographs_g6(
        node_count: int,
        connected_only: bool = True,
) -> list[str]:
    """
    Generate cographs in graph6 format using parallel processing,
    returning all results in memory (no batching, no temporary files).

    Parameters
    ----------
    node_count : int
        Number of vertices.
    connected_only : bool, optional
        If True, generate only connected cographs.

    Returns
    -------
    list[str]
        All graph6 strings generated.
    """

    num_processes = max(1, mp.cpu_count() // 3)

    if connected_only:
        generator = generate_connected_cotree_structures
    else:
        generator = generate_all_cotree_structures

    results: list[str] = []

    with mp.Pool(num_processes) as pool:
        for g6 in pool.imap_unordered(
                _structure_to_g6_optimized_worker,
                generator(node_count, 0),
                chunksize=100
        ):
            results.append(g6)

    return results


def generate_cotree_images(
        node_count: int,
        output_dir: str = "cotree_images",
) -> int:
    """
    Generate JPG images for all canonical cotrees with a given number of leaves.

    Cotree structures are generated by ``generate_all_cotree_structures`` and
    rendered as JPG files using ``render_cotree_jpg``. All images are written
    to ``output_dir``.

    Parameters
    ----------
    node_count : int
        Number of leaves in the cotrees to generate.
    output_dir : str, optional
        Directory where the generated JPG files will be written.

    Returns
    -------
    int
        Total number of cotree images generated.

    Raises
    ------
    NotADirectoryError
        If ``output_dir`` exists and is not a directory.
    """

    total = 0

    if os.path.exists(output_dir) and not os.path.isdir(output_dir):
        raise NotADirectoryError(
            f"output_dir must be a directory, got: {output_dir}"
        )

    os.makedirs(output_dir, exist_ok=True)

    for structure in generate_all_cotree_structures(node_count, 0):
        render_cotree_jpg(structure, node_count, output_dir)
        total += 1

    return total

